package recipemanagement_api.entity;

import java.util.ArrayList;
import java.util.List;

import org.springframework.data.annotation.Id;

import org.springframework.data.mongodb.core.mapping.Document;
import java.util.ArrayList;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
@Document(collection = "recipes")






public class Recipe {
	


@Id
private String id; // Auto-generated by MongoDB

private int cookingtime;
private List<String> ingredients;
private List<String> instructions;

// Add these if missing:
public void setIngredients(List<String> ingredients) {
    this.ingredients = ingredients;
}

private String title;
private String category;
public String getId() {
	return id;
}
public void setId(String id) {
	this.id = id;
}
public int getCookingtime() {
	return cookingtime;
}
public void setCookingtime(int cookingtime) {
	this.cookingtime = cookingtime;
}


public String getTitle() {
	return title;
}
public void setTitle(String title) {
	this.title = title;
}
public String getCategory() {
	return category;
}
public void setCategory(String category) {
	this.category = category;
}
public List<String> getInstructions() {
	return instructions;
}
public void setInstructions(List<String> instructions) {
	this.instructions = instructions;
}
public List<String> getIngredients() {
	return ingredients;
}

}
